ILLEGAL_FUNCTION = 0x01
ILLEGAL_DATA_ADDRESS = 0x02
ILLEGAL_DATA_VALUE = 0x03
SERVER_FAILURE = 0x04a
SERVER_BUSY = 0x06

COILS_OFFSET = 0
DISCRETE_INPUTS_OFFSET = 10000
INPUT_REGISTERS_OFFSET = 30000
HOLDING_REGISTERS_OFFSET = 40000

# True for database, False for JSON
DB = False
DB_HOST = ""
DB_USER = ""
DB_PASSWORD = ""

# True will create the json file
JSON = False
JSON_PATH = r"../Resources/storage.json"
